Documentation Update
ropod-project/black-box-tools pull request #1
Opened 2020-04-22 06:35 UTC by AhmedFaisal95

This pull request updates the documentation of this repository.

2020-04-23 04:17 UTC, alex-mitrevski approved these changes
I suggest we also update the list of functions in the different modules (in the README) before we merge.

2020-04-23 04:31 UTC, alex-mitrevski requested changes
I forgot to mention this, but could you please add the missing dependencies to the `requirements.txt` file?

2020-04-24 13:55 UTC, AhmedFaisal95 commented
> I forgot to mention this, but could you please add the missing dependencies to the `requirements.txt` file?

Most of the dependencies missing from the README were already in the `requirements.txt` file. I've added the couple missing.

2020-04-24 15:21 UTC, alex-mitrevski approved these changes

2020-04-24 15:22 UTC, merged